---
name: Verifying Installation

on:
  push:
    branches:
      - main

jobs:
  verify_installation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build, Install and Verify
        run: |
          gcc --version
          make all clean install
          next-prayer --version
          next-prayer --help
          next-prayer --all
          next-prayer --prev
          next-prayer --next
          next-prayer --elapsed
          next-prayer --left
          next-prayer --hijri
          next-prayer --adhan
